# Generated by Django 2.2.14 on 2026-05-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fraud_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PAYMENT', 'Thanh toan'), ('TRANSFER', 'Chuyen tien'), ('CASH_IN', 'Nap vi'), ('CASH_OUT', 'Rut tien'), ('DEBIT', 'Thanh toan hoa don')], default='PAYMENT', help_text='PaySim transaction type mapped to Vietnamese e-wallet services', max_length=32),
        ),
    ]
